In [1]:
# !pip install gensim
# !pip install python-Levenshtein

In [2]:
import gensim
import pandas as pd

In [3]:
df=pd.read_excel(r'training_data_with_augmentation_nlp_done.xlsx')
df.head()

,SHIPMENT_ID,DOCUMENT_ID,REMOTE_LOCATION,DOCUMENT_TYPE,TEXT_CONTENT,text
0,KX-D7I0-109,Jzg2XHurxjUOvTrmzuzf,1950156944-2124289811-44413_44436shippingdocs-...,0,PO#: 44413 / 44436\nORDER\nPALLET\n1-8\n9-16\n...,order pallet load detail sku cpe cpe empti box...
1,KX-J4J4-2,7Y986NV4O6fKCUtGUqZM,1954265047-326617438-TerminalHandlingCharges-H...,0,PayCargo\n• Created by KlearNow Corp from Klea...,paycargo creat klearnow corp klearnow corp sep...
2,KX-J4J4-2,c0eQC0f4FEvK5p3Y9GBh,1954265047-326617438-TerminalHandlingCharges-H...,0,Payment Details\nPayCargo\nMethod\nOvernight\n...,payment detail paycargo method overnight trans...
3,KX-E5G4-5767,0q2UC7nnnqw21hPzQcOY,1964909868-1563419258-AR_221203591-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...
4,KX-E5G4-5767,ytk1qRbji8Ra13tl98qs,1964909868-480001211-AR_22118434-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...


In [4]:
# counter = 0

# for index, i in enumerate(df['text']):
#     i = i.replace('\n', ' ')
#     for word in str(i).split(" "):
#         if len(word) > 15:
#             counter+=1
#             print()
#             print(len(word))
#             print(word)
#             break
# counter
# # df['text'][0]

In [5]:
df = df[df.text.str.contains(' ', na=False)]

review_text = df.text.apply(gensim.utils.simple_preprocess)

In [6]:
review_text

0        [order, pallet, load, detail, sku, cpe, cpe, e...
1        [paycargo, creat, klearnow, corp, klearnow, co...
2        [payment, detail, paycargo, method, overnight,...
3        [great, luck, inc, western, way, torranc, tel,...
4        [great, luck, inc, western, way, torranc, tel,...
                               ...                        
57995    [port, date, entri, enter, import, feder, expr...
57996    [port, date, entri, mark, number, packag, pc, ...
57997    [treasuri, int, custon, servic, instruct, reve...
57998    [port, date, entri, enter, import, feder, expr...
57999    [klearnow, import, immun, carrier, name, manif...
Name: text, Length: 57949, dtype: object

In [7]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=1,
    workers=4,
)

In [8]:
model.build_vocab(review_text, progress_per=1000)

In [9]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(55728895, 59292220)

In [10]:
# model.save("./word2vec-using-gensim.model")

In [11]:
from gensim.models import KeyedVectors

In [12]:
# Store just the words + their trained embeddings.
word_vectors = model.wv
word_vectors.save("word2vec_augmented_augmented_updated_nlp_done.wordvectors")

In [13]:
wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')

In [14]:
wv['zone']

memmap([-5.334834  , -2.2692323 , -0.02085055, -1.1687164 , -0.56529695,
        -1.5031846 ,  2.110912  ,  2.2222714 , -2.462092  , -3.7215068 ,
         2.634744  , -8.29192   , -2.3884685 , -6.8127246 ,  4.0409822 ,
         0.20610695,  3.7719436 , -5.776942  , -0.07047461, -2.866592  ,
         2.0164862 ,  0.43191683,  3.8776083 ,  1.4517026 , -1.564811  ,
         3.4140487 ,  1.8209527 , -1.7018458 ,  2.9071972 , -2.253235  ,
        -2.8482685 , -3.2771196 ,  3.0757465 ,  1.3232231 , -1.7622226 ,
        -2.3932464 ,  6.259707  , -4.529584  , -5.283004  , -1.7246083 ,
        -2.9130826 ,  0.541146  , -1.0257425 ,  5.5625267 , -1.9315841 ,
        -1.5619366 ,  3.0161617 , -2.478564  , -5.2619047 ,  5.224968  ,
         4.437704  , -3.6889586 , -1.3429602 , -3.727466  , -1.82786   ,
        -3.1675687 , -0.13676101, -2.6350741 , -4.1591206 , -4.443542  ,
        -1.5793754 ,  6.524507  ,  6.5533977 ,  5.8057275 ,  1.4358901 ,
         4.5385175 ,  5.256713  , -0.53369296,  0.0

In [18]:
model.wv.most_similar("arrive")

[('cargaison', 0.8254327774047852),
 ('partir', 0.6133756041526794),
 ('gratuit', 0.6026078462600708),
 ('traspaso', 0.588858962059021),
 ('livraison', 0.5869613885879517),
 ('effet', 0.5753169655799866),
 ('regl', 0.56508469581604),
 ('purement', 0.55959552526474),
 ('devi', 0.556580126285553),
 ('sommat', 0.5560755133628845)]

In [13]:
model.wv['zone']

array([ 2.1940963 ,  0.4429837 ,  2.3147984 ,  0.4350213 , -0.4377893 ,
       -5.6672096 , -2.1142457 , -5.6569486 ,  1.2992312 , -1.1548837 ,
       -0.5078694 ,  0.68569714, -2.3663352 ,  2.1393414 , -2.5903983 ,
        5.844661  , -3.401175  ,  3.8852763 , -0.09768377, -5.155677  ,
       -1.0896169 ,  3.189435  ,  2.5981596 ,  1.7715316 ,  1.3449788 ,
       -2.6989472 , -2.380281  ,  1.2197142 ,  2.6309357 , -3.446495  ,
        0.1687182 , -2.4902835 ,  3.8933907 ,  3.4750464 , -0.47670013,
       -2.9742477 ,  6.798027  ,  6.6562834 , -1.6140373 , -2.7393146 ,
        2.821489  ,  1.6204611 ,  2.1116917 , -3.6750906 ,  0.47692996,
        0.82885367, -3.1719425 ,  1.5617213 ,  2.7796667 , -0.860116  ,
        0.5109334 , -1.6217035 , -0.06462263,  0.94484085, -2.5953856 ,
        1.7360655 ,  1.417726  ,  7.8530073 , -1.1783617 , -2.7110698 ,
        6.7110386 ,  1.0168141 , -3.9171584 ,  1.0129513 , -1.2386391 ,
        0.93157315,  0.46547416,  0.6365279 ,  3.9556234 ,  7.14

In [15]:
words = list(model.wv.index_to_key)

In [17]:
# words

In [20]:
import torch 
import torch.nn as nn

In [22]:
# Get a dictionary mapping of the vocab
word_map = {
    word:idx
    for idx,word in enumerate(model.wv.key_to_index, start=2)
}
# word_map

In [23]:
 (
    df
    .text
    .apply(lambda x: x.split(" "))
)[0]

['tivani',
 'vietnam',
 'furnitureco',
 'ltdno',
 'dongkhoistreet',
 'zone',
 'hoaphuward',
 'thudaumotc',
 'binhduongprovincetel',
 'fax',
 'stuffingdetail',
 'loadingchartloadingd',
 'ponumb',
 'stockton',
 'cafinaldestin',
 'tivanyportofdischargeetdd',
 'containers',
 'hcetad',
 'sep',
 'oct',
 'acontainernumb',
 'tcnu',
 'sealnumb',
 'itemcodeorderqtyloadedqtyremarkssa',
 'ag',
 'jvsertaocaugustinepulloutqueensizesofaandtrackarmupholsterygradesojava',
 'uso',
 'withpipingburlywood',
 'additionalinform',
 'detail',
 'replacementpart',
 'sampleitem',
 'sertaccaugustinepulloutqueensizesofaandtrackarmupholsterygrad',
 'java',
 'withpipingburlywood',
 'othersitem',
 'factoryitem',
 'otherfactoryitern',
 'fumigationfe',
 'cartonscarton',
 'remark',
 'loadedbi',
 'factorycomekordatkiteyanycheckedbi',
 'factorycheckedandconfirmedbycustomerrep',
 'lifestylesolutionsqc',
 'name',
 'tivanynam',
 'tivanynam',
 'idno',
 'idno',
 'idno',
 'date',
 'date',
 'date']

In [24]:
training_sentence_data = (
    df
    .text
    .apply(lambda x: list(map(lambda word: word_map[word] if word in word_map else 1, x.split(" "))))
)
print(training_sentence_data[0])

[2039, 146, 19343, 11675, 19302, 308, 15069, 18171, 1, 50, 38821, 1, 24471, 2890, 1, 1, 12538, 30239, 118, 331, 56894, 928, 11644, 1, 2043, 1, 6993, 1, 1, 176, 26700, 26625, 1, 4898, 1, 30247, 26612, 1, 37147, 1, 222, 30250, 1, 1, 1, 10, 37146, 37146, 24357, 24357, 24357, 5, 5, 5]


In [26]:
sentence_length = df.text.apply(lambda x: x.split(" ")).apply(len).max()
sentence_length

3502

In [27]:
training_sentence_data = (
    list(
        map(
            lambda x: pd.np.pad(x, (0, sentence_length-len(x))), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.


array([ 2039,   146, 19343, ...,     0,     0,     0])

In [28]:
torch.LongTensor(training_sentence_data[0])

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [29]:
training_sentence_data = (
    list(
        map(
            lambda x: torch.LongTensor(x), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [30]:
model.wv.vectors.shape

(68614, 100)

In [31]:
word_vectors_for_training = pd.np.insert(
    model.wv.vectors,   
    0, 
    pd.np.random.uniform(model.wv.vectors.min(),model.wv.vectors.max(),100),
    axis=0
)

word_vectors_for_training = pd.np.insert(
    word_vectors_for_training,   
    0, 
    pd.np.zeros(100),
    axis=0
)
word_vectors_for_training = torch.FloatTensor(word_vectors_for_training)
word_vectors_for_training.shape

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  # This is added back by InteractiveShellApp.init_path()


torch.Size([68616, 100])

In [32]:
class FirstNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.embedding_layer = nn.EmbeddingBag.from_pretrained(word_vectors_for_training, mode="mean")
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, data_input):
        embedded_data_input = self.embedding_layer(data_input)
        output_layer1 = self.layer1(embedded_data_input)
        output_layer1 = self.relu(output_layer1)
        output_layer2 = self.layer2(output_layer1)
        # return the predictions but drop the axis
        return output_layer2.squeeze()