In [1]:
# !pip install gensim
# !pip install python-Levenshtein

In [2]:
import gensim
import pandas as pd

In [3]:
df=pd.read_excel(r'finalTrainingData.xlsx')
df.tail()

,desc,hts
513157,lavish home reversible alternative comforter,9404908522
513158,wawel czekolada dark 70% gorzka 100g,1806329000
513159,et 1l cracw 1,4821109000
513160,"camilo c , table60 marble w / gr",9403600000
513161,"32 h wooden block joy porch sign""",9505105020


In [4]:
# df.loc[df['REMOTE_LOCATION']=='48759-3434153-CastlegateHBL_MAEUNPO1369700_HDMUNBOZ36987900_HDMUNBOZ369879A1-1.png','text']

In [5]:
# df=df.loc[df['DOCUMENT_TYPE']!=0]
df['hts'].value_counts()

6911103750    6159
9403608081    3887
9403509045    2689
5702420000    1897
9401616011    1783
              ... 
6702104000    1500
2001909791    1500
6910100030    1500
9402100000    1500
6306229030    1500
Name: hts, Length: 336, dtype: int64

In [6]:
len(df)

513162

In [7]:
# counter = 0

# for index, i in enumerate(df['text']):
#     i = i.replace('\n', ' ')
#     for word in str(i).split(" "):
#         if len(word) > 15:
#             counter+=1
#             print()
#             print(len(word))
#             print(word)
#             break
# counter
# # df['text'][0]

In [8]:
df = df[df.desc.str.contains(' ', na=False)]

review_text = df.desc.apply(gensim.utils.simple_preprocess)

In [9]:
review_text

0           [wexford, red, dinner, plates, rd, gb, wexgrnb]
1                                       [std, lr, ell, wpb]
2                      [cukierki, nimm, witaminami, storck]
3                                  [load, levelling, valve]
4                          [filtr, oleju, fiat, doblo, jtd]
                                ...                        
513157    [lavish, home, reversible, alternative, comfor...
513158                     [wawel, czekolada, dark, gorzka]
513159                                          [et, cracw]
513160                          [camilo, table, marble, gr]
513161                    [wooden, block, joy, porch, sign]
Name: desc, Length: 496744, dtype: object

In [10]:
# review_text[15183]

In [11]:
# from gensim.test.utils import common_texts, get_tmpfile
# from gensim.models import Word2Vec
# from gensim.models.callbacks import CallbackAny2Vec

# class callback(CallbackAny2Vec):
#     '''Callback to print loss after each epoch.'''

#     def __init__(self):
#         self.epoch = 0

#     def on_epoch_end(self, model):
#         loss = model.get_latest_training_loss()
#         print('Loss after epoch {}: {}'.format(self.epoch, loss))
#         self.epoch += 1

# # model = Word2Vec(common_texts, size=100, window=5, min_count=1, 
# #                  compute_loss=True, callbacks=[callback()])

In [12]:
# model = gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=6e-5,
#     vector_size=300,
#     compute_loss=True, callbacks=[callback()],
#     epochs=7
# )

In [13]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=6e-5
# )

In [14]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-6
# )

In [15]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-4
# )

In [16]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-5
# )

In [17]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-5
# )

In [18]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-4
# )

In [19]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-5
# )

In [20]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-6
# )

In [21]:
model= gensim.models.Word2Vec(
    window=7,
    min_count=1,
    workers=4,
    sample=6e-5,vector_size=300
)

# model_2= gensim.models.Word2Vec(
#     window=7,
#     min_count=1,
#     workers=4,
#     sample=6e-5,vector_size=300
# )



In [22]:
model.build_vocab(review_text, progress_per=1000)
# model.build_vocab(review_text, progress_per=1000)

In [23]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(7113273, 11440270)

In [24]:
# sentences=list(df.text)

In [25]:
# !pip install --upgrade gensim

In [26]:
# pip list

In [27]:
# from gensim.sklearn_api import W2VTransformer
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import accuracy_score, make_scorer

# s_obj = W2VTransformer(size=100)

# parameters = {'window':(5,10,15),'min_count':(1,2,4)}

# # s_model = GridSearchCV(s_obj,parameters,cv=2)
# s_model = GridSearchCV(s_obj,parameters, scoring=make_scorer(accuracy_score))

# s_model.fit(review_text)

# print(s_model.best_params_)

In [28]:
# from gensim.test.utils import common_texts
# common_texts

In [29]:
# model.save("./word2vec-using-gensim.model")

In [30]:
from gensim.models import KeyedVectors

In [31]:
# Store just the words + their trained embeddings.
word_vectors = model.wv
word_vectors.save("word2vec_htsFinalTrainingData.wordvectors")

In [32]:
wv = KeyedVectors.load("word2vec_htsFinalTrainingData.wordvectors", mmap='r')

In [33]:
# wv_2 = KeyedVectors.load("word2vec_augmented_augmented_updated_nlp_done_lemmatized_6e-5_300_win_7.wordvectors", mmap='r')

In [34]:
# wv_2['zone']

In [35]:
# wv['zone']

In [36]:
# wv_2.most_similar('vessel')

In [39]:
model.wv.most_similar("chair")

[('rostock', 0.845950722694397),
 ('treatment', 0.8436311483383179),
 ('xy', 0.8319669365882874),
 ('blizzard', 0.8275760412216187),
 ('lashes', 0.8261263370513916),
 ('ivette', 0.8218719959259033),
 ('reagan', 0.818252682685852),
 ('shumacher', 0.8155107498168945),
 ('bellevue', 0.8112028241157532),
 ('dining', 0.8099753856658936)]

In [41]:
model.wv.most_similar("furniture")

[('couch', 0.8384209275245667),
 ('wheeled', 0.8337068557739258),
 ('office', 0.7836503982543945),
 ('coventry', 0.7763373851776123),
 ('colorado', 0.7671786546707153),
 ('closet', 0.7581614851951599),
 ('linden', 0.7581315636634827),
 ('olstered', 0.7578588128089905),
 ('moving', 0.755333662033081),
 ('bolste', 0.7550448179244995)]

In [39]:
model.wv.most_similar("zone")

[('town', 0.7556388974189758),
 ('district', 0.7454279065132141),
 ('develop', 0.7255854606628418),
 ('industri', 0.7248048186302185),
 ('provinc', 0.7162231802940369),
 ('sheng', 0.695965588092804),
 ('zhejiang', 0.682959258556366),
 ('huizhou', 0.6727529764175415),
 ('jiang', 0.6694082021713257),
 ('luoyang', 0.6670336127281189)]

In [ ]:
# wv_2.most_similar('zone')

In [44]:
wv_2.most_similar('weight')

[('gross', 0.8439235687255859),
 ('kg', 0.7610828280448914),
 ('total', 0.7282893657684326),
 ('quantity', 0.7198747992515564),
 ('measurement', 0.7183003425598145),
 ('cbm', 0.685063898563385),
 ('package', 0.6820922493934631),
 ('pallet', 0.6777692437171936),
 ('net', 0.6775811314582825),
 ('description', 0.6684989333152771)]

In [37]:
model.wv.most_similar("weight")

[('gross', 0.838156521320343),
 ('kg', 0.7437127232551575),
 ('measur', 0.7319930791854858),
 ('total', 0.7295935153961182),
 ('quantiti', 0.7114863395690918),
 ('packag', 0.6879239082336426),
 ('pallet', 0.6876823902130127),
 ('net', 0.6783446073532104),
 ('nett', 0.6572309136390686),
 ('cbm', 0.6396167874336243)]

In [37]:
model.wv.most_similar("weight")

[('gross', 0.8531695604324341),
 ('kg', 0.7877658605575562),
 ('measur', 0.787743330001831),
 ('total', 0.7318695783615112),
 ('quantiti', 0.7200117111206055),
 ('packag', 0.7128152251243591),
 ('cbm', 0.6974779367446899),
 ('pallet', 0.6914093494415283),
 ('kilo', 0.6871155500411987),
 ('net', 0.6692990660667419)]

In [36]:
# model.wv.most_similar("notice")

In [32]:
model.wv['zone']

array([-1.88528016e-01, -4.31258053e-01,  5.79042375e-01,  3.05005938e-01,
       -4.35556412e-01, -1.36682093e-01, -1.42982468e-01,  1.37720034e-01,
       -6.75675154e-01, -5.76798558e-01,  4.40493263e-02,  5.39672911e-01,
       -5.94543219e-01,  6.86391532e-01, -1.16921455e-01, -2.55154729e-01,
       -2.98690647e-01, -2.23723575e-01, -7.18584180e-01,  6.14137888e-01,
       -6.69286260e-03, -5.77483773e-01,  1.25561881e+00,  2.19308138e-01,
       -5.68856955e-01,  1.56532609e+00, -4.54786301e-01, -1.12937093e+00,
       -7.12194383e-01, -4.22803849e-01,  6.08687401e-01,  5.37833273e-01,
       -7.82175362e-01,  1.29907501e+00, -1.40590322e+00, -1.24604087e-02,
        8.79062355e-01, -5.89669272e-02, -5.64991415e-01,  3.30133021e-01,
       -1.13320313e-02, -1.00313556e+00,  5.67413330e-01,  7.92829633e-01,
       -1.37735689e+00, -3.66172403e-01,  3.96012306e-01,  1.97842017e-01,
       -8.90435278e-01,  1.61869979e+00, -5.96987426e-01, -9.74520385e-01,
        6.19746521e-02, -

In [15]:
words = list(model.wv.index_to_key)

In [17]:
# words

In [20]:
import torch 
import torch.nn as nn

In [22]:
# Get a dictionary mapping of the vocab
word_map = {
    word:idx
    for idx,word in enumerate(model.wv.key_to_index, start=2)
}
# word_map

In [23]:
 (
    df
    .text
    .apply(lambda x: x.split(" "))
)[0]

['tivani',
 'vietnam',
 'furnitureco',
 'ltdno',
 'dongkhoistreet',
 'zone',
 'hoaphuward',
 'thudaumotc',
 'binhduongprovincetel',
 'fax',
 'stuffingdetail',
 'loadingchartloadingd',
 'ponumb',
 'stockton',
 'cafinaldestin',
 'tivanyportofdischargeetdd',
 'containers',
 'hcetad',
 'sep',
 'oct',
 'acontainernumb',
 'tcnu',
 'sealnumb',
 'itemcodeorderqtyloadedqtyremarkssa',
 'ag',
 'jvsertaocaugustinepulloutqueensizesofaandtrackarmupholsterygradesojava',
 'uso',
 'withpipingburlywood',
 'additionalinform',
 'detail',
 'replacementpart',
 'sampleitem',
 'sertaccaugustinepulloutqueensizesofaandtrackarmupholsterygrad',
 'java',
 'withpipingburlywood',
 'othersitem',
 'factoryitem',
 'otherfactoryitern',
 'fumigationfe',
 'cartonscarton',
 'remark',
 'loadedbi',
 'factorycomekordatkiteyanycheckedbi',
 'factorycheckedandconfirmedbycustomerrep',
 'lifestylesolutionsqc',
 'name',
 'tivanynam',
 'tivanynam',
 'idno',
 'idno',
 'idno',
 'date',
 'date',
 'date']

In [24]:
training_sentence_data = (
    df
    .text
    .apply(lambda x: list(map(lambda word: word_map[word] if word in word_map else 1, x.split(" "))))
)
print(training_sentence_data[0])

[2039, 146, 19343, 11675, 19302, 308, 15069, 18171, 1, 50, 38821, 1, 24471, 2890, 1, 1, 12538, 30239, 118, 331, 56894, 928, 11644, 1, 2043, 1, 6993, 1, 1, 176, 26700, 26625, 1, 4898, 1, 30247, 26612, 1, 37147, 1, 222, 30250, 1, 1, 1, 10, 37146, 37146, 24357, 24357, 24357, 5, 5, 5]


In [26]:
sentence_length = df.text.apply(lambda x: x.split(" ")).apply(len).max()
sentence_length

3502

In [27]:
training_sentence_data = (
    list(
        map(
            lambda x: pd.np.pad(x, (0, sentence_length-len(x))), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.


array([ 2039,   146, 19343, ...,     0,     0,     0])

In [28]:
torch.LongTensor(training_sentence_data[0])

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [29]:
training_sentence_data = (
    list(
        map(
            lambda x: torch.LongTensor(x), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [30]:
model.wv.vectors.shape

(68614, 100)

In [31]:
word_vectors_for_training = pd.np.insert(
    model.wv.vectors,   
    0, 
    pd.np.random.uniform(model.wv.vectors.min(),model.wv.vectors.max(),100),
    axis=0
)

word_vectors_for_training = pd.np.insert(
    word_vectors_for_training,   
    0, 
    pd.np.zeros(100),
    axis=0
)
word_vectors_for_training = torch.FloatTensor(word_vectors_for_training)
word_vectors_for_training.shape

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  # This is added back by InteractiveShellApp.init_path()


torch.Size([68616, 100])

In [32]:
class FirstNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.embedding_layer = nn.EmbeddingBag.from_pretrained(word_vectors_for_training, mode="mean")
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, data_input):
        embedded_data_input = self.embedding_layer(data_input)
        output_layer1 = self.layer1(embedded_data_input)
        output_layer1 = self.relu(output_layer1)
        output_layer2 = self.layer2(output_layer1)
        # return the predictions but drop the axis
        return output_layer2.squeeze()

In [35]:
df=pd.read_excel(r'training_data_with_augmentation_nlp_done.xlsx')
df.head()

,SHIPMENT_ID,DOCUMENT_ID,REMOTE_LOCATION,DOCUMENT_TYPE,TEXT_CONTENT,text
0,KX-D7I0-109,Jzg2XHurxjUOvTrmzuzf,1950156944-2124289811-44413_44436shippingdocs-...,0,PO#: 44413 / 44436\nORDER\nPALLET\n1-8\n9-16\n...,order pallet load detail sku cpe cpe empti box...
1,KX-J4J4-2,7Y986NV4O6fKCUtGUqZM,1954265047-326617438-TerminalHandlingCharges-H...,0,PayCargo\n• Created by KlearNow Corp from Klea...,paycargo creat klearnow corp klearnow corp sep...
2,KX-J4J4-2,c0eQC0f4FEvK5p3Y9GBh,1954265047-326617438-TerminalHandlingCharges-H...,0,Payment Details\nPayCargo\nMethod\nOvernight\n...,payment detail paycargo method overnight trans...
3,KX-E5G4-5767,0q2UC7nnnqw21hPzQcOY,1964909868-1563419258-AR_221203591-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...
4,KX-E5G4-5767,ytk1qRbji8Ra13tl98qs,1964909868-480001211-AR_22118434-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...


In [40]:
df['data_type']=df['DOCUMENT_ID'].apply(lambda x:'augmented' if 'augmented' in x else 'original')

In [43]:
df.to_excel(r'training_data_with_augmentation_nlp_done_stemmed_final.xlsx',index=False)